[context.production]
  environment = { NODE_VERSION = "14.16.0" }
[[headers]]
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer Policy = "no-referrer"
