[context.production]
  environment = { NODE_VERSION = "14.16.0" }
[[headers]]
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src https:"
  Content-Security-Policy: script-src 'self'
  Permissions-Policy: "fullscreen=(), geolocation=()"
